accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ExpenseCategoryListView,
    AccountListView,
    ReceiptListView,
    CategoryCreateView,
    AccountCreateView,
    ReceiptCreateView,
)

urlpatterns = [
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="receiptcategories_list",
    ),
    path("accounts/", AccountListView.as_view(), name="receiptaccounts_list"),
    path("", ReceiptListView.as_view(), name="home"),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="receiptcategory_create",
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="receiptaccount_create",
    ),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your views here.

# function signup(request)
def signup(request):
    # if the request method is "POST", then
    if request.method == "POST":
        # form = UserCreationForm(request.POST)
        form = UserCreationForm(request.POST)
        # if the form is valid, then
        if form.is_valid():
            # username = the "username" value from the request.POST dictionary
            username = request.POST.get("username")
            # password = the "password1" value from the request.POST dictionary
            password = request.POST.get("password1")
            # user = create a new user using username and password
            user = User.objects.create_user(username, password=password)
            # save the user object
            user.save()
            # login the user with the request and user object
            login(request, user)
            # return a redirect to the "home" path
            return redirect("home")
    # otherwise,
    else:
        # form = UserCreationForm(request.POST)
        form = UserCreationForm(request.POST)
    # context = dictionary with key "form" and value form
    context = {"form": form}
    # return render with request, "registration/signup.html", and the context
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

# from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView


from django.contrib.auth.mixins import LoginRequiredMixin

from receipts.models import Account, ExpenseCategory, Receipt


# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receiptcategories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receiptaccounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receiptcategories/new.html"
    fields = ["name"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        category = form.save(commit=False)
        category.owner = self.request.user
        category.save()
        return redirect("home")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receiptaccounts/new.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        return redirect("home")


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    # QUESTION:
    # do "category" and "account" go inside of the fields? not sure...
    # I'd assume they don't since they don't directly take an input...
    # these fields are supposed to be created via the CategoryCreateView and AccountCreateView?
    # we'll see.
    # ANSWER (AFTER TESTING IT):
    # yes!! "category" and "account" do go inside the fields below.
    # they show up as dropdowns.
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        return redirect("home")

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <title>Accounts</title>
</head>

<body>
  <header>

    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'home' %}">View Receipts</a>
        </li>
        <li>
          <a href="{% url 'receipt_create' %}">Create Receipt</a>
        </li>
        <li>
          <a href="{% url 'receiptaccounts_list' %}">View Accounts</a>
        </li>
        <li>
          <a href="{% url 'receiptaccount_create' %}">Create Accounts</a>
        </li>
        <li>
          <a href="{% url 'receiptcategories_list' %}">View Expense Categories</a>
        </li>
        <li>
          <a href="{% url 'receiptcategory_create' %}">Create Expense Categories</a>
        </li>
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'signup' %}">Sign Up</a>
        </li>
        <li>
          <a href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </nav>


  </header>
  <main>
    {% block content %}
    {% endblock content %}
  </main>
</body>

</html>

receipts/templates/receiptaccounts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Receipt Accounts</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for account in account_list %}
    <tr>
      <td>{{ account.name }}</td>
      <td>{{ account.number }}</td>
      <td>{{ account.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

receipts/templates/receiptaccounts/new.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <h1>Create Receipt Account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create Receipt Account</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receiptcategories/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Expense Categories</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for expensecategory in expensecategory_list %}
    <tr>
      <td>{{ expensecategory.name }}</td>
      <td>{{ expensecategory.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

receipts/templates/receiptcategories/new.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <h1>Create Expense Category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create Expense Category</button>
      </div>
    </form>
  </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<h1> Receipts </h1>
<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </tr>
  </thead>
  <tbody>
    {% for receipt in receipt_list %}
    <tr>
      <td>{{ receipt.vendor }}</td>
      {% comment %} show only 2 decimal places {% endcomment %}
      <td>$ {{ receipt.total|floatformat:2 }}</td>
      {% comment %} show only 2 decimal places {% endcomment %}
      <td>$ {{ receipt.tax|floatformat:2 }}</td>
      <td>{{ receipt.date|date:"m-d-Y" }}</td>
      <td>{{ receipt.category }}</td>
      <td>{{ receipt.account|default_if_none:"Cash" }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

receipts/templates/receipts/new.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div>
        <button>Create Receipt</button>
      </div>
    </form>
  </main>
{% endblock content %}